export default {
    recoProducts: [
        {
            brandName: 'Tatcha',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'Tatcha - The Kissu Lip Mask',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isNew: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: true,
                listPrice: '$29.00',
                skuId: '2315315',
                skuType: 'Standard',
                variationType: 'Color',
                variationValue: 'Original',
                variationTypeDisplayName: 'Color'
            },
            displayName: 'The Kissu Lip Mask',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s2315315-main-zoom.jpg?imwidth=270&pb=2020-03-sephora-clean-2019',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s2315315-av-01-zoom.jpg?imwidth=270',
            moreColors: 0,
            productId: 'P453225',
            rating: '0.0',
            reviews: '0',
            targetUrl: '/product/tatcha-the-kissu-lip-mask-P453225?skuId=2315315',
            sponsored: false
        },
        {
            brandName: 'LANEIGE',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'LANEIGE - Lip Treatment Balm',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isNew: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: true,
                listPrice: '$25.00',
                skuId: '2449908',
                skuType: 'Standard',
                variationType: 'Size',
                variationValue: '0.35 oz/ 10g',
                variationTypeDisplayName: 'Size'
            },
            displayName: 'Lip Treatment Balm',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s2449908-main-zoom.jpg?imwidth=270',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s2449908-av-02-zoom.jpg?imwidth=270',
            moreColors: 0,
            productId: 'P469490',
            rating: '0.0',
            reviews: '0',
            targetUrl: '/product/laneige-lip-treatment-balm-P469490?skuId=2449908',
            sponsored: false
        },
        {
            brandName: 'tarte',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'tarte - Lights, Camera, Lashes™ 4-in-1 Mascara',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: false,
                listPrice: '$15.00 - $25.00',
                skuId: '862417',
                skuType: 'Standard',
                variationType: 'Color',
                variationValue: 'Black',
                variationTypeDisplayName: 'Color'
            },
            displayName: 'Lights, Camera, Lashes™ 4-in-1 Mascara',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s862417-main-zoom.jpg?imwidth=270',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s862417-av-11-zoom.jpg?imwidth=270',
            moreColors: 1,
            productId: 'P111902',
            rating: '4.3488',
            reviews: '86',
            targetUrl: '/product/lights-camera-lashes-P111902?skuId=862417',
            sponsored: false
        },
        {
            brandName: 'REN Clean Skincare',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'REN Clean Skincare - Evercalm™ Barrier Support Antioxidant Moisturizer',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isNew: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: false,
                listPrice: '$52.00',
                skuId: '2114577',
                skuType: 'Standard',
                variationType: 'Size',
                variationValue: '1.7 oz/ 50 mL',
                variationTypeDisplayName: 'Size'
            },
            displayName: 'Evercalm™ Barrier Support Antioxidant Moisturizer',
            heroImage:
                'https://azre1-qa04.internal.sephora.com/productimages/sku/s2114577-main-zoom.jpg?imwidth=270&pb=clean-planet-positive-badge-2021',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s2114577-av-6-zoom.jpg?imwidth=270',
            moreColors: 0,
            productId: 'P214002',
            rating: '5.0',
            reviews: '2',
            targetUrl: '/product/evercalm-global-protection-day-cream-P214002?skuId=2114577',
            sponsored: false
        },
        {
            brandName: 'Kate Somerville',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'Kate Somerville - Goat Milk Moisturizing Cream',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isNew: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: false,
                listPrice: '$76.00',
                skuId: '1809003',
                skuType: 'Standard',
                variationType: 'Size',
                variationValue: '1.7 oz/ 50 mL',
                variationTypeDisplayName: 'Size'
            },
            displayName: 'Goat Milk Moisturizing Cream',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s1809003-main-zoom.jpg?imwidth=270',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/product/p232910-av-02-zoom.jpg?imwidth=270',
            moreColors: 0,
            productId: 'P232910',
            rating: '0.0',
            reviews: '0',
            targetUrl: '/product/goat-milk-moisturizing-cream-P232910?skuId=1809003',
            sponsored: false
        },
        {
            brandName: 'Shiseido',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'Shiseido - Eyelash Curler',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: false,
                listPrice: '$24.00',
                skuId: '1201474',
                skuType: 'Standard',
                variationType: 'Type',
                variationValue: 'Eyelash Curler',
                variationTypeDisplayName: 'Type'
            },
            displayName: 'Eyelash Curler',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s1201474-main-zoom.jpg?imwidth=270&pb=2020-03-allure-best-2018',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s1201474-av-6-zoom.jpg?imwidth=270',
            moreColors: 0,
            productId: 'P244437',
            rating: '4.0',
            reviews: '4',
            targetUrl: '/product/eyelash-curler-P244437?skuId=1201474',
            sponsored: false
        },
        {
            brandName: 'First Aid Beauty',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'First Aid Beauty - Ultra Repair® Cream Intense Hydration',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: false,
                listPrice: '$15.00 - $48.00',
                skuId: '1217744',
                skuType: 'Standard',
                variationType: 'Size',
                variationValue: '6 oz/ 170 g',
                variationTypeDisplayName: 'Size'
            },
            displayName: 'Ultra Repair® Cream Intense Hydration',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s1217744-main-zoom.jpg?imwidth=270&pb=2020-03-sephora-clean-2019',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s1217744-av-01-zoom.jpg?imwidth=270',
            moreColors: 0,
            productId: 'P248407',
            rating: '4.0',
            reviews: '9',
            targetUrl: '/product/ultra-repair-cream-intense-hydration-P248407?skuId=1217744',
            sponsored: false
        },
        {
            brandName: 'Bobbi Brown',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'Bobbi Brown - Vitamin Enriched Face Base Primer Moisturizer',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: false,
                listPrice: '$24.00 - $99.00',
                skuId: '1292820',
                skuType: 'Standard',
                variationType: 'Size',
                variationValue: '1.7 oz/ 50 mL',
                variationTypeDisplayName: 'Size'
            },
            displayName: 'Vitamin Enriched Face Base Primer Moisturizer',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s1292820-main-zoom.jpg?imwidth=270',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s1292820-av-15-zoom.jpg?imwidth=270',
            moreColors: 0,
            productId: 'P270594',
            rating: '0.0',
            reviews: '0',
            targetUrl: '/product/vitamin-enriched-face-base-P270594?skuId=1292820',
            sponsored: false
        },
        {
            brandName: 'SEPHORA COLLECTION',
            currentSku: {
                biExclusiveLevel: 'none',
                imageAltText: 'SEPHORA COLLECTION - Retractable EyeBrow Pencil - Waterproof',
                isAppExclusive: false,
                isBI: false,
                isBest: false,
                isFirstAccess: false,
                isLimitedEdition: false,
                isLimitedTimeOffer: false,
                isNatural: false,
                isNew: false,
                isOnlineOnly: false,
                isOrganic: false,
                isSephoraExclusive: true,
                listPrice: '$12.00',
                skuId: '2242998',
                skuType: 'Standard',
                variationType: 'Color',
                variationValue: '01 Blonde',
                variationTypeDisplayName: 'Color'
            },
            displayName: 'Retractable EyeBrow Pencil - Waterproof',
            heroImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s2242998-main-zoom.jpg?imwidth=270&pb=2023-03-sephora-value-2023',
            altImage: 'https://azre1-qa04.internal.sephora.com/productimages/sku/s2242998-av-08-zoom.jpg?imwidth=270',
            moreColors: 10,
            productId: 'P286513',
            rating: '4.0714',
            reviews: '14',
            targetUrl: '/product/retractable-brow-pencil-waterproof-P286513?skuId=2242998',
            sponsored: false
        }
    ]
};
