import RougeExclusiveRewardsCarouselLayout from 'components/Content/ProductListLayout/RougeExclusiveRewardsCarouselLayout/RougeExclusiveRewardsCarouselLayout';

export default RougeExclusiveRewardsCarouselLayout;
