name: Rover Check on PR to Release

on:
  pull_request:
    branches:
      - release

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  rover-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo 'export PATH="$HOME/.rover/bin:$PATH"' >> $GITHUB_ENV
          /home/runner/.rover/bin/rover --version
      - name: Verify Apollo Authentication
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
        run: /home/runner/.rover/bin/rover config whoami

      - name: Run Rover subgraph check on Dev, QA, Perf Environments.
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
        run: |
          graph_name=Sephora-Enterprise-Graph
          schema_path=omni-product-service/src/main/resources/schema/schema.graphqls
          Application=omni-product-service
          echo "Running rover subgraph check on Preview Env"
          /home/runner/.rover/bin/rover subgraph check $graph_name@preview --schema $schema_path --name $Application
          echo "Running rover subgraph check on Prod Env"
          /home/runner/.rover/bin/rover subgraph check $graph_name@prod --schema $schema_path --name $Application
