query GuestBookingClientDetails($guestBookingClientDetailsInput: GuestBookingClientDetailsInput!) {
  guestBookingClientDetails(guestBookingClientDetailsInput: $guestBookingClientDetailsInput) {
    clientState
  }
}