const STORE_LOOKUP_TABLE = {
    'US': {
        'en': {
            AA: 'Armed Forces America',
            AE: 'Armed Forces Europe',
            AK: 'Alaska',
            AL: 'Alabama',
            AP: 'Armed Forces Pacific',
            AR: 'Arkansas',
            AZ: 'Arizona',
            CA: 'California',
            CO: 'Colorado',
            CT: 'Connecticut',
            DC: 'District of Columbia',
            DE: 'Delaware',
            FL: 'Florida',
            GA: 'Georgia',
            HI: 'Hawaii',
            IA: 'Iowa',
            ID: 'Idaho',
            IL: 'Illinois',
            IN: 'Indiana',
            KS: 'Kansas',
            KY: 'Kentucky',
            LA: 'Louisiana',
            MA: 'Massachusetts',
            MD: 'Maryland',
            ME: 'Maine',
            MI: 'Michigan',
            MN: 'Minnesota',
            MO: 'Missouri',
            MS: 'Mississippi',
            MT: 'Montana',
            NC: 'North Carolina',
            ND: 'North Dakota',
            NE: 'Nebraska',
            NH: 'New Hampshire',
            NJ: 'New Jersey',
            NM: 'New Mexico',
            NV: 'Nevada',
            NY: 'New York',
            OH: 'Ohio',
            OK: 'Oklahoma',
            OR: 'Oregon',
            PA: 'Pennsylvania',
            PR: 'Puerto Rico',
            PW: 'Palau',
            RI: 'Rhode Island',
            SC: 'South Carolina',
            SD: 'South Dakota',
            TN: 'Tennessee',
            TX: 'Texas',
            UT: 'Utah',
            VA: 'Virginia',
            VT: 'Vermont',
            WA: 'Washington',
            WI: 'Wisconsin',
            WV: 'West Virginia',
            WY: 'Wyoming'
        },
        'fr': {
            AA: 'Forces armées américaines',
            AE: 'Forces armées - Europe',
            AK: 'Alaska',
            AL: 'Alabama',
            AP: 'Forces armées - Pacifique',
            AR: 'Arkansas',
            AZ: 'Arizona',
            CA: 'Californie',
            CO: 'Colorado',
            CT: 'Connecticut',
            DC: 'District de Columbia',
            DE: 'Delaware',
            FL: 'Floride',
            GA: 'Georgie',
            HI: 'Hawaï',
            IA: 'Iowa',
            ID: 'Idaho',
            IL: 'Illinois',
            IN: 'Indiana',
            KS: 'Kansas',
            KY: 'Kentucky',
            LA: 'Louisiane',
            MA: 'Massachusetts',
            MD: 'Maryland',
            ME: 'Maine',
            MI: 'Michigan',
            MN: 'Minnesota',
            MO: 'Missouri',
            MS: 'Mississippi',
            MT: 'Montana',
            NC: 'Caroline du Nord',
            ND: 'Dakota du Nord',
            NE: 'Nebraska',
            NH: 'New Hampshire',
            NJ: 'New Jersey',
            NM: 'Nouveau-Mexique',
            NV: 'Nevada',
            NY: 'New York',
            OH: 'Ohio',
            OK: 'Oklahoma',
            OR: 'Oregon',
            PA: 'Pennsylvanie',
            PR: 'Puerto Rico',
            PW: 'Palaos',
            RI: 'Rhode Island',
            SC: 'Caroline du Sud',
            SD: 'Dakota du Sud',
            TN: 'Tennessee',
            TX: 'Texas',
            UT: 'Utah',
            VA: 'Virginie',
            VT: 'Vermont',
            WA: 'Washington',
            WI: 'Wisconsin',
            WV: 'Virginie occidentale',
            WY: 'Wyoming'
        }

    },
    'CA': {
        'en': {
            AB: 'Alberta',
            BC: 'British Columbia',
            MB: 'Manitoba',
            NB: 'New Brunswick',
            NL: 'Newfoundland and Labrador',
            NS: 'Nova Scotia',
            NT: 'Northwest Territories',
            NU: 'Nunavut',
            ON: 'Ontario',
            PE: 'Prince Edward Island',
            QC: 'Quebec',
            SK: 'Saskatchewan',
            YT: 'Yukon'
        },
        'fr': {
            AB: 'Alberta',
            BC: 'Colombie-Britannique',
            MB: 'Manitoba',
            NB: 'Nouveau-Brunswick',
            NL: 'Terre-Neuve-et-Labrador',
            NS: 'Nouvelle-Écosse',
            NT: 'Territoires du Nord-Ouest',
            NU: 'Nunavut',
            ON: 'Ontario',
            PE: 'Île-du-Prince-Édouard',
            QC: 'Québec',
            SK: 'Saskatchewan',
            YT: 'Yukon'
        }
    }
};
export default STORE_LOOKUP_TABLE;
